name: Copy image between registries

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
      workflow_id:
        required: true
        type: string
      

jobs:
  copy:
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
      IMAGE_NAME: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.AWS_REPOSITORY }}    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      -
        name: Login to dev ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
      -
        name: Copy
        env:
          VERSION: ${{ inputs.version }}
          WORKFLOW_ID: ${{ inputs.workflow_id }}
        run: |
          docker buildx imagetools create \
            --tag ${IMAGE_NAME}:${VERSION}_stable \
            ${IMAGE_NAME}:${VERSION}_b${WORKFLOW_ID}
